server:
  port: 8080

spring:
  application:
    name: app


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://103.94.159.179;database=remit_db
    username: dev
    password: sbdb@141

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true

